# Generated by Django 5.2.5 on 2025-08-28 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('pothole_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Chưa sửa'), ('fixed', 'Đã sửa')], default='active', max_length=10)),
                ('confidence_avg', models.FloatField(default=0)),
                ('detections_count', models.PositiveIntegerField(default=1)),
                ('first_detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PotholeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('size', models.CharField(choices=[('small', 'Nhỏ'), ('large', 'Lớn')], max_length=10)),
                ('confidence', models.FloatField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('pothole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='my_app.pothole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PotholeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='potholes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pothole_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_app.potholedetection')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(choices=[('pothole', 'Pothole'), ('no_pothole', 'No Pothole')], default='no_pothole', max_length=20)),
                ('used_in_training', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
