# Generated by Django 5.2.5 on 2025-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholedetection',
            name='level',
            field=models.CharField(choices=[('small', 'Nhỏ'), ('medium', 'Trung bình'), ('large', 'Lớn')], max_length=10),
        ),
    ]
